#!/bin/bash

DOMAIN=`hostname -d`
TMPFILE="/tmp/test-sensu-alert-for-${USER}.json"

cat <<EOF >"${TMPFILE}"
{
  "name": "test_alert_for_${USER}",
  "interval": 0,
  "alert_after": 0,
  "realert_every": "1",
  "runbook": "unknown",
  "sla": "No SLA defined.",
  "dependencies": [],
  "team": "noop",
  "slack_channels": [],
  "notification_email": "${USER}@${DOMAIN}",
  "ticket": false,
  "project": false,
  "page": false,
  "tip": "this is a test alert",
  "output": "Test output from send-test-sensu-alert",
  "status": 2,
  "command": "send-test-sensu-alert",
  "ttl": null
}
EOF

$EDITOR "$TMPFILE"
if [[ $? -eq 0 ]]; then

  if cat "$TMPFILE" | tr -d "\n" | jq . > /dev/null ; then
    echo "Sending the alert to the localhost:3030 socket!"
    cat "$TMPFILE" | tr -d "\n"  > /dev/tcp/localhost/3030
    echo
    echo "Resolve your check with:"
    echo "sensu-cli resolve `hostname -f` `jq .'name' $TMPFILE`"
  else
    echo "Error: Invalid JSON?"
    echo "Running jq to see what it says:"
    jq . "$TMPFILE"
  fi

fi
